#!/usr/bin/env node
/**
 * Runs worker/test/questions.json against a deployed (or `wrangler dev
 * --remote`) chat endpoint, records reply/sources/latency for each, and
 * writes TEST_RESULTS.md at the repo root.
 *
 * Usage:
 *   CHAT_URL=https://careshmajadhav-chat.<subdomain>.workers.dev/api/chat npm run test:live
 *   CHAT_URL=http://localhost:8787/api/chat npm run test:live   (wrangler dev --remote)
 */
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CHAT_URL = process.env.CHAT_URL;

if (!CHAT_URL) {
  console.error("Set CHAT_URL to the deployed /api/chat endpoint, e.g.:");
  console.error("  CHAT_URL=https://careshmajadhav-chat.<subdomain>.workers.dev/api/chat npm run test:live");
  process.exit(1);
}

async function sendTurn(message, history, sessionId) {
  const start = Date.now();
  const res = await fetch(CHAT_URL, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ message, history, sessionId }),
  });

  const contentType = res.headers.get("content-type") || "";
  let reply = "";
  let sources = [];

  if (contentType.includes("application/json")) {
    const data = await res.json();
    reply = data.reply || data.error || JSON.stringify(data);
    sources = data.sources || [];
  } else {
    reply = await res.text();
    const sourcesHeader = res.headers.get("x-chat-sources");
    if (sourcesHeader) {
      try { sources = JSON.parse(decodeURIComponent(sourcesHeader)); } catch { /* ignore */ }
    }
  }

  return { reply, sources, latencyMs: Date.now() - start, status: res.status };
}

function truncate(text, n = 220) {
  const clean = (text || "").replace(/\s+/g, " ").trim();
  return clean.length > n ? clean.slice(0, n) + "…" : clean;
}

async function main() {
  const questions = JSON.parse(await readFile(path.join(__dirname, "questions.json"), "utf8"));
  const rows = [];

  for (const q of questions) {
    const sessionId = `test_${q.id}_${Date.now()}`;
    const history = [];
    let last = null;

    const turns = q.turns || [q.message];
    for (const turnMessage of turns) {
      last = await sendTurn(turnMessage, history, sessionId);
      history.push({ role: "user", content: turnMessage });
      history.push({ role: "assistant", content: last.reply });
      console.log(`[${q.id}] (${q.lang}) "${truncate(turnMessage, 60)}" -> ${last.status}, ${last.latencyMs}ms`);
    }

    rows.push({
      id: q.id,
      lang: q.lang,
      category: q.category,
      question: turns[turns.length - 1],
      reply: truncate(last.reply),
      sources: (last.sources || []).map((s) => s.url).join(", "),
      latencyMs: last.latencyMs,
      status: last.status,
    });
  }

  const header = "| # | Lang | Category | Question (last turn) | Reply (truncated) | Sources | Latency (ms) | HTTP |\n" +
    "|---|------|----------|------------------------|--------------------|---------|---------------|------|\n";
  const body = rows
    .map((r) => `| ${r.id} | ${r.lang} | ${r.category} | ${r.question.replace(/\|/g, "\\|")} | ${r.reply.replace(/\|/g, "\\|")} | ${r.sources} | ${r.latencyMs} | ${r.status} |`)
    .join("\n");

  const avgLatency = Math.round(rows.reduce((s, r) => s + r.latencyMs, 0) / rows.length);
  const out = `# Test results\n\nGenerated by \`npm run test:live\` against \`${CHAT_URL}\`.\n\nAverage latency: ${avgLatency}ms across ${rows.length} requests.\n\n${header}${body}\n`;

  await writeFile(path.join(__dirname, "..", "..", "TEST_RESULTS.md"), out, "utf8");
  console.log(`\nWrote TEST_RESULTS.md (avg latency ${avgLatency}ms)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
